controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Image;
use app\models\Profile;
use app\models\SendEmailForm;
use app\models\UploadFile;
use app\models\User;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\SignupForm;
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\AccountActivation;
use app\models\ResetPasswordForm;
use yii\web\UploadedFile;

class SiteController extends AddController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => [
                            'logout',
                            'reset-password',
                            'activate-account',
                            'add-profile',
                            'profile-delete',
                            'profile-edit',
                            'image-delete',
                            'add-image'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        return $this->render('index',[

            'title' => Yii::$app->name,
            'keywords' => '',
            'description' => '',
            'profiles' => Profile::find()->all()
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('profile');
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays profile page.
     *
     * @return string
     */
    public function actionProfile()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        return $this->render('profile', [
            'title' => Yii::$app->user->identity->username ?? '',
            'keywords' => '',
            'description' => '',
            'users' => Profile::find()->where(['user_id' => Yii::$app->user->identity->id])->all()
        ]);
    }

    public function actionAddProfile()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }


        $image = new UploadFile();
        $profile = new Profile();

//
//        if (Yii::$app->request->isAjax) {
//
//            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            if ($profile->load(Yii::$app->request->post()) && $image->load(Yii::$app->request->post())) {


                if ($new_profile = $profile->addProfile()) {
                    $image->image = UploadedFile::getInstances($image, 'image');

                    if ($images = $image->upload($new_profile->id)) {
                        $save_image = new Image();
                        $save_image->addImages($images, $new_profile->id);

                    }
                    return $this->redirect('/profile');

                } else {

                    return $this->redirect('/add-profile');

                }
            }
//        }

        return $this->render('addProfile', [
            'title' => 'Создание нового профиля',
            'keywords' => '',
            'description' => '',
            'profile' => $profile,
            'id' => null,
            'image' => $image,
            'link_profile' => ['label' => Yii::$app->user->identity->username, 'url' => '/profile'],


        ]);

    }

    /**
     * Displays setting page.
     *
     * @return string
     */
    public function actionProfileDelete($id=0)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $profile = new Profile();

        if (Yii::$app->request->isAjax) {
            if (Yii::$app->request->post()) {

                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

                $id = (int)Yii::$app->request->post()['id'];
                $profile->deleteProfile($id);
                return $profile;
            }
        }

        $profile->deleteProfile((int)$id);

        return $this->redirect('/profile');

    }
    /**
     * Displays setting page.
     *
     * @return string
     */
    public function actionImageDelete($id=0)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new Image();

        if (Yii::$app->request->isAjax) {
            if (Yii::$app->request->post()) {

                $id = (int)Yii::$app->request->post()['id'];


                $profile = $model->deleteImage($id);

                return $this->redirect('/profile-edit/' . $profile);
            }
        }

        return $this->redirect('/profile-edit/' . $model->deleteImage((int)$id));

    }
    /**
     * Displays setting page.
     *
     * @return string
     */
    public function actionProfileEdit($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $profile = Profile::findOne((int)$id);
        $images = Image::findAll(['profile_id' => (int)$id]);

        $image = new UploadFile();

        if ($profile->load(Yii::$app->request->post()) && $image->load(Yii::$app->request->post())) {

            $profile_id = (int)Yii::$app->request->post()['id'];

            if ($profile->updateProfile($profile_id)) {
                $image->image = UploadedFile::getInstances($image, 'image');

                if ($images = $image->upload($profile_id)) {
                    $save_image = new Image();
                    $save_image->addImages($images, $profile_id);

                }
                return $this->redirect('/profile-edit/'.$profile_id);

            } else {

                return $this->redirect('/profile-edit/'.$profile_id);

            }
        }

        return $this->render('profileEdit', [
            'title' => 'Редактирование профиля',
            'id' => $id,
            'keywords' => '',
            'description' => '',
            'profile' => $profile,
            'image' => $image,
            'countFile' => (count($images) >= 5) ? null : 5 - count($images),
            'images' => $images,
            'link_profile' => ['label' => Yii::$app->user->identity->username, 'url' => '/profile'],


        ]);

    }


    public function actionSignup()
    {
        $model = Yii::$app->params['emailActivation']
            ? new SignupForm(['scenario' => 'emailActivation'])
            : new SignupForm();


        if ($model->load(Yii::$app->request->post())) {

            if ($user = $model->signup()) {

                if ($user->status === User::STATUS_ACTIVE) {

                    if (Yii::$app->getUser()->login($user)) {
                        return $this->redirect('profile');
                    }
                } else {

                    if ($model->sendActivationEmail($user)) {
                        Yii::$app->session->setFlash(
                            'success',
                            'Письмо отправлено по email <strong>'
                                . Html::encode($user->email)
                                . '</strong> (проверьте папку спам)');
                    } else {
                        Yii::$app->session->setFlash(
                            'error',
                            'Ошибка, письмо не отправлено.'
                        );

                        Yii::error('Ошибка отправки письма');
                    }

                    return $this->refresh();
                }
            } else {
                Yii::$app->session->setFlash(
                    'error',
                    'Возникла ошибка при регистрации.'
                );

                Yii::error('Ошибка отправки письма');

                return $this->refresh();
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }


    public function actionSendEmail()
    {
        $model = new SendEmailForm();

        if ($model->load(Yii::$app->request->post())) {

            if ($model->validate()) {

                if ($model->sendEmail()) {

                    Yii::$app->getSession()->setFlash(
                        'warning',
                        'Проверьте емайл.');

                    return $this->redirect('profile');
                } else {

                    Yii::$app->getSession()->setFlash(
                        'error',
                        'Нельзя сбросить пароль.');
                }
            }
        }
        return $this->render('sendEmail', [
            'model' => $model,
        ]);
    }

views/site/addProfile.php
<?php use yii\helpers\Html; ?>
<?php use yii\widgets\ActiveForm; ?>
<?php use yii\widgets\MaskedInput; ?>
<?php use kartik\file\FileInput; ?>

<?php
$this->render('@app/views/includes/seo', [
    'title' => $title ?? Yii::$app->name,
    'keywords' => $keywords ?? '',
    'description' => $description ?? ''
]); ?>

<?php $this->params['breadcrumbs'][] = $link_profile; ?>
<?php $this->params['breadcrumbs'][] = $title; ?>
<div class="site-about">
    <h1><?= Html::encode($title) ?></h1>


    <div class="hidden">
        <div class="alert">

            <a href="#" class="close" data-dismiss="alert">&times;</a>

            <span>

            </span>

        </div>
    </div>


    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data',  'class' => 'add_profile',]]) ?>
    <?= $form->field($profile, 'name')->textInput() ?>
    <?=  $form->field($profile, 'email')->input('email') ?>
    <?=  $form->field($profile, 'address')->textInput() ?>
    <?=  $form->field($profile, 'phone')->widget(MaskedInput::className(), [
        'mask' => '+375 (99) 999-99-99',
        'options' => [
            'class' => 'form-control placeholder-style',
            'placeholder' => ('Телефон')
        ],
        'clientOptions' => [
            'clearIncomplete' => true
        ]
    ]) ?>

    <?= $form->field($image, 'image[]')->widget(FileInput::classname(), [
        'name' => 'test[]',
        'options' => ['multiple' => true, 'accept' => 'image/*'],
        'pluginOptions' => [
            'allowedFileExtensions'=>['jpg', 'png'],
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false
        ]
    ]);?>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary btn-add-profile']);?>

    <?php ActiveForm::end() ?>
</div>
<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU&amp;load=SuggestView&amp;onload=onLoad"></script>
<script>
    function onLoad (ymaps) {
        var suggestView = new ymaps.SuggestView('profile-address', {results: 5, offset: [20, 30]});
    }
</script>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = $title;
?>
<div class="site-index">

    <?php if(count($profiles) > 0): ?>
        <div class="m-t-30">
            <table class="table table-striped table-bordered data-table">
                <thead>
                <tr>
                    <th width="30">ID</th>
                    <th width="100" class="text-center">Имя</th>
                    <th width="100" class="text-center">Email</th>
                    <th width="150" class="text-center">Адрес</th>
                    <th width="20" class="text-center">Номер телефона</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($profiles as $count => $profile): ?>
                    <tr>
                        <td>
                            <?= ++$count; ?>
                        </td>
                        <td class="text-right">
                            <?= $profile->name ?>
                        </td>
                        <td class="text-right">
                            <?= $profile->email ?>
                        </td>
                        <td class="text-center">
                            <?= $profile->address ?>
                        </td>
                        <td class="text-center">
                            <a href="tel:<?= $profile->phone; ?> ">
                                <?= $profile->phone; ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>

    <?php endif; ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Войти';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Заполните форму:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>
        <div style="color:#999;margin:1em 0">
            Если вы забыли пароль, перейдите по ссылке <?= Html::a('изменить', ['site/send-email']) ?>.
        </div>
        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/profile.php
<?php use yii\helpers\Html; ?>
<?php use yii\helpers\Url; ?>

<?php
$this->render('@app/views/includes/seo', [
    'title' => $title ?? Yii::$app->name,
    'keywords' => $keywords ?? '',
    'description' => $description ?? ''
]); ?>

<?php $this->params['breadcrumbs'][] = $title; ?>
<div class="site-about">
    <h1><?= Html::encode($title) ?></h1>


    <div class="hidden">
        <div class="alert">

            <a href="#" class="close" data-dismiss="alert">&times;</a>

            <span>

            </span>

        </div>
    </div>
    <p>
        <a href="/add-profile">Добавить новый профиль</a>
    </p>
    <?php if(count($users) > 0): ?>
        <div class="m-t-30">
            <table class="table table-striped table-bordered data-table">
                <thead>
                <tr>
                    <th width="30">ID</th>
                    <th width="150" class="text-center">Имя</th>
                    <th width="150" class="text-center">Email</th>
                    <th width="100" class="text-center">Фото</th>
                    <th width="10" class="text-center"></th>
                    <th width="10" class="text-center"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($users as $count => $user): ?>
                    <tr>
                        <td>
                            <?= ++$count; ?>
                        </td>
                        <td class="text-right">
                            <?= $user->name?>
                        </td>
                        <td class="text-right">
                            <?= $user->email?>
                        </td>
                        <td class="text-center">
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                    <?php foreach($user->getSlides() as $image): ?>
                                        <div class="swiper-slide">
                                            <?= $image?>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </td>
                        <td class="text-center">
                            <a href="<?= Url::to(['/profile-edit/'.$user->id]); ?>"
                               class="link-edit" data-id="<?= $user->id?>">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </td>
                        <td  class="text-center">
                            <a href="<?= Url::to(['/profile-delete', 'id' => $user->id]); ?>"
                               class="link-del" data-id="<?= $user->id?>">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>

    <?php endif; ?>

</div>

views/site/profileEdit.php
<?php use yii\helpers\Html; ?>
<?php use yii\widgets\ActiveForm; ?>
<?php use yii\widgets\MaskedInput; ?>
<?php use kartik\file\FileInput; ?>

<?php
$this->render('@app/views/includes/seo', [
    'title' => $title ?? Yii::$app->name,
    'keywords' => $keywords ?? '',
    'description' => $description ?? ''
]); ?>

<?php $this->params['breadcrumbs'][] = $link_profile; ?>
<?php $this->params['breadcrumbs'][] = $title; ?>
<div class="site-about">
    <h1><?= Html::encode($title) ?></h1>


    <div class="hidden">
        <div class="alert">

            <a href="#" class="close" data-dismiss="alert">&times;</a>

            <span>

            </span>

        </div>
    </div>


    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data',  'class' => 'add_profile',]]) ?>
    <?= $form->field($profile, 'name')->textInput() ?>
    <input type="hidden" name="id" value="<?= $id ?>">

    <?=  $form->field($profile, 'email')->input('email') ?>
    <?=  $form->field($profile, 'address')->textInput() ?>
    <?=  $form->field($profile, 'phone')->widget(MaskedInput::className(), [
        'mask' => '+375 (99) 999-99-99',
        'options' => [
            'class' => 'form-control placeholder-style',
            'placeholder' => ('Телефон')
        ],
        'clientOptions' => [
            'clearIncomplete' => true
        ]
    ]) ?>
    <div class="file-image-change">
        <?php include(Yii::getAlias('@app/views/includes/file_image.php')); ?>
    </div>

    <?php if(count($images) > 0): ?>
        <div class="m-t-30">
            <table class="table table-striped table-bordered data-table">
                <thead>
                <tr>
                    <th width="10" class="text-center">ID</th>
                    <th width="100" class="text-center">Фото</th>
                    <th width="10" class="text-center">
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($images as $count => $image): ?>
                    <tr>
                        <td>
                            <?= ++$count; ?>
                        </td>
                        <td class="text-center">
                            <a href="<?= $image->image?>" target="_blank">
                                <img src="<?= $profile->uploadThumbnail($id, $image->image)?>" alt="">
                            </a>
                        </td>
                        <td  class="text-center">
                            <a href="<?= \yii\helpers\Url::to(['/image-delete', 'id' => $image->id]); ?>"
                               class="link-image-del" data-id="<?= $image->id?>">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>

    <?php endif; ?>

    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary btn-add-profile']);?>

    <?php ActiveForm::end() ?>
</div>

<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU&amp;load=SuggestView&amp;onload=onLoad"></script>
<script>
    function onLoad (ymaps) {
        var suggestView = new ymaps.SuggestView('profile-address', {results: 5, offset: [20, 30]});
    }
</script>

views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\models\ResetPasswordForm */
/* @var $form ActiveForm */
?>
<div class="main-resetPassword">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- main-resetPassword -->

views/site/sendEmail.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\models\SendEmailForm */
/* @var $form ActiveForm */
?>
<div class="main-sendEmail">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
    <i>(проверьте папку спан)</i>

</div><!-- main-sendEmail -->

views/site/signup.php
<?php use yii\helpers\Html; ?>
<?php use yii\bootstrap\ActiveForm; ?>
<?php $this->title = 'Регистрация'; ?>
<?php $this->params['breadcrumbs'][] = $this->title; ?>

<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Чтобы использовать возможности этого приложения, зарегистрируйтесь</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
            <?= $form->field($model, 'email') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <div class="form-group">
                <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
            <?php if ($model->scenario === 'emailActivation'): ?>
                <i>На указанный email придет письмо для активации аккаунта</i>
            <?php endif; ?>

        </div>
    </div>
</div>